---
- import_playbook: preseed.yml

- hosts: all
  tasks:
    - name: Creating packages directory
      become: yes
      file:
        path: "{{ packages_directory }}"
        state: directory
        owner: "{{ packages_directory_owner|default('root') }}"
        group: "{{ packages_directory_group|default('users') }}"
        mode: "{{ packages_directory_mode|default('0775') }}"

