---
- hosts: all
  tasks:
    - name: Managing apt keys
      become: yes
      apt_key:
        id: "{{ item.id }}"
        keyserver: "{{ item.keyserver|default(default_app_keyserver) }}"
        state: "{{ item.state|default('present') }}"
      with_items: "{{ apt_keys }}"

    - name: Managing apt repositories
      become: yes
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state|default('present') }}"
        codename: "{{ item.codename|default('') }}"
        update_cache: yes
      with_items: "{{ apt_repositories }}"

    - name: Managing apt packages
      become: yes
      apt:
        name: "{{ item.name }}={{ item.version|default('*') }}"
        state: "{{ item.state|default('present') }}"
        cache_valid_time: 3600
      with_items: "{{ apt_packages }}"

